### ISSUE TITLE
Use personal domain name

### ISSUE THREAD

**Issue by Arithmomaniac** [shushugah/shushugah.github.io#1]
https://github.com/shushugah/shushugah.github.io/blob/ec0c5cc57cbc079a7f9f6fcbeaee91d45f4bd429/_config.yml#L15

Now that you've held your own job since school, branding based on where you went to school becomes a liability. Getting your own domain is [like ~$10/yr](https://www.namecheap.com/), and they usually come with email forwarding (this is what I do.)

**Comment by shushugah** [comment]
Done :)
